name: Wheels

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
  release:
    types:
      - published

jobs:
  build:
    name: Build wheel ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-20.04", "macos-11", "windows-latest" ]
    env:
      BUILD_COMMIT: HEAD
      CIBW_BEFORE_ALL_LINUX: sh ci/docker-fixes.sh
      CIBW_BEFORE_ALL_MACOS: sh ci/osx-fixes.sh
      CIBW_ARCHS_LINUX: x86_64
      CIBW_ARCHS_MACOS: x86_64 universal2
      # Building for one python version is enough, since this is a
      # ctypes-based 'universal binary wheel' (py2.py3-none-*) not
      # linked to a specific python version or implementation.
      CIBW_BUILD: "cp39-*"
      CIBW_SKIP: "*-musllinux*"
      CIBW_BUILD_VERBOSITY_WINDOWS: 1
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: "Set up MSYS2 (Windows)"
        uses: msys2/setup-msys2@v2
        if: startsWith(matrix.os, 'windows')
        with:
          release: false
          install: >-
            autotools
            git
            mingw-w64-i686-ragel
            mingw-w64-x86_64-ragel
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Update path (Mac)
        if: startsWith(matrix.os, 'macos')
        run: |
          echo "/usr/local/opt/libtool/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/ragel/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/flex/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/automake/bin" >> $GITHUB_PATH
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel
      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
      - name: Check wheels metadata
        run: pipx run twine check dist/*.whl
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.whl

  deploy:
    name: Upload if release
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
